#!/bedrock/libexec/busybox sh

upper() {
    if which python3 &> /dev/null
    then
        echo "$@" | python3 -c "import sys;x=sys.stdin.read();print(x[0].upper() + x[1:],end='')"
        return
    fi
    echo "$@"
}

log() {
    echo "$@" >&2
    echo "# $@"
}

if ! [ -d /bedrock ]
then
	log "No bedrock linux install, not continuing"
	exit
fi

if [ -z "$GRUB_CMDLINE_LINUX" ]
then
	GRUB_CMDLINE_LINUX="rw quiet enforcing=0 lang=en_US kmap=us"
fi

init_root=$(grep -oE 'root=[^ ]*' /proc/cmdline | sed s/root=//)
# DEBUG ONLY
#init_root="UUID=your-uuid-goes-here"
# END DEBUG
root=$(echo $init_root | sed 's#/dev/##')
log "debug - root is $root"
if echo "$root" | grep -q UUID=
then
    grub_root=
    grub_search="search --no-floppy --fs-uuid --set=root "$(echo "$root"|sed 's/UUID=//')
    init_root="$root" # like UUID=aldsfjlasdjfladjsflakdjsf
else
    if [ -z "$root" ]
    then
        root=$(lsblk -r|grep /bedrock/strata/bedrock| tail -n 1 | cut -d ' ' -f 1) # not ideal
        log "debug - root was garbage so guessing $root"
    fi

    using_gpt="true"
    if ! which gdisk &> /dev/null
    then
        using_gpt="false"
    else
        if gdisk -l /dev/"$(echo "$root"|cut -c -3)"|grep -q "GPT: not present" # another dirty hack
        then
            using_gpt="false"
        fi
    fi

    grub_root="(hd"
    case $(echo "$root"|cut -c -3) in
        sda|nvme0)
            grub_root=$grub_root"0" ;;
        sdb)
            grub_root=$grub_root"1" ;;
        sdc)
            grub_root=$grub_root"2" ;;
        sdd)
            grub_root=$grub_root"3" ;;
    esac
    grub_root=$grub_root","
    if [ "$using_gpt" = false ]
    then
        grub_root="$grub_root"msdos
    fi
    grub_root="$grub_root"$(echo "$root"|cut -c 4-)')'
fi # uuid/else

# as long as one of these works we're good
source /usr/share/grub/grub-mkconfig_lib
source "$pkgdatadir/grub-mkconfig_lib"


find_kernels() {
    list=
    for i in /boot/kernel-* /boot/vmlinuz-* ; do
        if test -f "$i"; then
            list="$list $i"
        fi
    done

    #linux=$(version_find_latest $list) # Do not double quote $list, it needs to expand
    #basename=$(basename "$linux")
    #version=$(echo "$basename" | sed -e "s,vmlinuz-,,g")
    #alt_version=$(echo "$version" | sed -e "s,\.old$,,g")
}

find_initrd_for_kernel() {
    initrd=
    for i in "initrd.img-${version}" "initrd-${version}.img" "initrd-${version}.gz" \
       "initrd-${version}" "initramfs-${version}.img" \
       "initrd.img-${alt_version}" "initrd-${alt_version}.img" \
       "initrd-${alt_version}" "initramfs-${alt_version}.img" \
       "initramfs-vmlinuz-${alt_version}.img" \
       "initramfs-genkernel-${version}" \
       "initramfs-genkernel-${alt_version}" \
       "initramfs-genkernel-${GENKERNEL_ARCH}-${version}" \
       "initramfs-genkernel-${GENKERNEL_ARCH}-${alt_version}"; do

        if [ -e "/boot/$i" ]
        then
            #if grub_file_is_not_garbage "$i"
            #then
                initrd="$i"
                break
            #fi
        fi
    done
}


 
list=
find_kernels
for linux in $list; do
    basename=$(basename "$linux")
    version=$(echo "$basename" | sed -e "s,vmlinuz-,,g")
    alt_version=$(echo "$version" | sed -e "s,\.old$,,g")
    find_initrd_for_kernel
    if [ -z "$initrd" ]
    then
        log "Kernel $linux does not appear to provide a matching initramfs for $linux . Please make sure you compiled with fuse support"
    fi
    log "Found kernel in $linux"
    path_to_kernel=/boot/

    for init_strata in $(brl list --enabled); do
        init="/sbin/init"
        echo "menuentry 'Bedrock Linux - kernel $linux - init from $(upper $init_strata) - $init' {"
        if ! [ -z "$grub_search" ]
        then
            echo "	$grub_search"
        fi
        # grub_root is like (hd0,msdos6)
        # path_to_kernel is like /bedrock/strata/fedora/boot/ (set to /boot/ for kernels in the rootfs)
        # basename is like vmlinuz-4.9
        echo "	linux $grub_root""$path_to_kernel""$basename" "$GRUB_CMDLINE_LINUX" rw init=/sbin/init root="$init_root" strata="$init_strata" strata_init="$init"
        if ! [ -z "$initrd" ]
        then
            echo "	initrd $grub_root""$path_to_kernel""$(basename $initrd)"
        fi

        echo "}"
    done
done
